{
    pkgs
}:

rec {

      hpc = pkgs.envModuleGen {
            name = "HPCrelease";
            description = "load BBP HPC environment generated by nix";
            packages = [ 
		            # circuit building
                            pkgs.functionalizer 
                            pkgs.touchdetector
                            pkgs.mvdtool
                            pkgs.highfive
                            pkgs.bluebuilder
                            pkgs.flatindexer

                            # cellular sim
                            pkgs.coreneuron
                            pkgs.mod2c
                            pkgs.neurodamus
                            pkgs.neuron
                            pkgs.reportinglib
        
                            # sub cellular sim
                            pkgs.steps-mpi

			    # point neuron
			    pkgs.nest

                            #utils
                            pkgs.bbp-mpi
                            
                            #python env for scientists
                            pkgs.python27Full                            
                            pkgs.python27Packages.numpy
                            pkgs.python27Packages.matplotlib
			    pkgs.python27Packages.six
                            pkgs.python27Packages.pandas
                                                        
                       ];
            extraContent = "prepend-path BBP_HOME $targetEnv/";                       
      };

      hpc-bgq = pkgs.envModuleGen {
            name = "HPCrelease_BGQ";
            description = "load BBP HPC environment on BGQ module generated by nix";
            packages = [ 
                            pkgs.functionalizer 
                            pkgs.touchdetector
                            pkgs.bluebuilder                            
                            pkgs.highfive
                            pkgs.mvdtool                            

                            # cellular sim
                            pkgs.coreneuron
                            pkgs.mod2c
                            pkgs.neurodamus
                            pkgs.neuron
                            pkgs.reportinglib
                       ];
            extraContent = "prepend-path BBP_HOME $targetEnv/";
      };


      python27 = with pkgs; envModuleGen rec {
            name = "python-2.7";
	    moduleFilePath = "python/2.7";
            description = "python 2.7 module generated by nix";
            packages = let pythonPkgs = python27Packages;
                         in
                        [
			    # basic C/C++ bundle for pip 
                            gcc
			    stdenv
			    # python and module collection
			    python 
			    pythonPkgs.pip
			    pythonPkgs.virtualenv
                            #pythonPkgs.numpy
                            #pythonPkgs.pandas                            
                            #pythonPkgs.pycurl
                            #pythonPkgs.h5py
                       ];
      };
      
      python34 = pkgs.envModuleGen rec {
            name = "python-3.4";
	    moduleFilePath = "python/3.4";
            description = "python 3.4 module generated by nix";
            packages = let pythonPkgs = pkgs.python34Packages;
                         in
                        [ 
                            pkgs.python34 
                            pythonPkgs.numpy
                            pythonPkgs.pandas                            
                            pythonPkgs.pycurl
                            pythonPkgs.h5py
                       ];
      };    


      rust = pkgs.envModuleGen rec {
            name = "rust-1.2";
            description = "rust platform module generated by nix";
            packages = [ 
                            pkgs.rustc
                            pkgs.cargo 
                       ];
      };    
 

      golang = pkgs.envModuleGen rec {
            name = "go-1.5";
            description = "golang and packages module generated by nix";
            packages = [ 
                            pkgs.goPackages.go
                            pkgs.goPackages.net
                            pkgs.goPackages.osext 
                       ];
      };  
      
      
      cmake = pkgs.envModuleGen rec {
            name = "cmake-3.0";
            description = "cmake 3.0 module generated by nix";
            packages = [ 
                            pkgs.cmake 
                       ];
      };    
      
      gcc52 = pkgs.envModuleGen rec {
            name = "gcc-5.2.0";
            description = "gcc 5.2.0 module generated by nix";
            packages = [ 
                            pkgs.gcc5 
                       ];
      };   
      
      
    R = pkgs.envModuleGen rec {
            name = "R-3.2.2";
            description = "R module generated by nix";
            packages = [ 
                            pkgs.R
                       ];
      };   

}
